[package]
name = "face_dataset_generator"
version = "0.1.0"
edition = "2021"

[dependencies]
rustface = "0.1"
image = "0.24"
imageproc = "0.23"
clap = { version = "4.0", features = ["derive"] }
anyhow = "1.0"
walkdir = "2.3"
[dev-dependencies]
tempfile = "3.8"
